### ISSUE TITLE
resume-schema, version 1.0.0

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/resume-schema#197]
Piggybacking off of #187 , I think resume-schema needs an new major version (that is, a version that breaks backwards compatibility with a new featureset).

Since @thomasdavis is super busy, I'll leave his issue, and open this one with a list of features already suggested that should be put into this new version.
- [ ] Fix the date issue, #198.
- [ ] .(Come to a consensus on and) add events, projects and non-professional experience, #201 
- [ ] Use bibJSON for publications, #194.
- [ ] Add a 'summary' to education (like for work), #185.
- [ ] Add work authorizations, #179.
- [ ] Figure out some way to add additional personal info, #41.
- [ ] Add resume tags, #203.
- [x] Add a metadata section, #204.

I'll update this as I go through them.

**Comment by thomasdavis** [comment]
Thanks Chris.

As we have done in the past, we should label issues with the pre-existing labels. Once consensus is reached, we should draw up a PR for it. 

Once a decent consensus is agreed upon for the PR, we can merge it in and then update the README change log.

**Comment by aloisdg** [comment]
Check #193 cc @stp-ip

**Comment by chrisdotcode** [comment]
Okay, those could be an excellent starting point. Thanks, @stp-ip. If you're still around, it would be nice to look through the commits with you.

**Comment by stp-ip** [comment]
Still around. stp on IRC.

**Comment by chrisdotcode** [comment]
Okay! We've had a lot of good discussion, and I believe it's more than time to start committing stuff.

We (the community) are more than in agreement on a lot of things, so let the pull requests commence. We'll start with the easy stuff, and move on to the big stuff in due time.

When and if anybody pull requests, please includes tests for your additions to the schema!

resume-cli is messed up in several places, but we should start by finalizing v1.0.0's schema first before touching the cli's codebase, or else we'll just be adding more unnecessary work if we change things.

**Comment by aloisdg** [comment]
If I can help in any way, just mention me!
