### ISSUE TITLE
Fix the date problem

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/resume-schema#198]
There are about three or so issues that are related to date parsing that will require changes to the schema and the parser in tandem.
- [x] ~~Seasons should be allowed in dates, #180.~~ Rejected
- [ ] Dates in `YYYY-MM` and `YYYY` should be valid, #142.
- [ ] Allows the empty string in `endDate` to represent the present, #150.
- [x] ~~Add custom date parser (maybe?),  #150.~~ Rejected. However, we still might be able to salvage some of the PRed code.
- [ ] Figure out how to represent ongoing work, #199.

This is the "master issue" I'll use to keep track of what they are.

**Comment by chrisdotcode** [comment]
I'm really not on board with adding a custom date parser, because anything "custom", is by definition, not machine readable.

The intent of that issue was that technically valid ISO8601 dates were not getting parsed, and I think once that is solved, we should stop there.

**Comment by KOLANICH** [comment]
I think we don't need separate fields for season and years. We should just combine startDate and endDate into a subschema dateRange and use it everywhere instead of date.

**Comment by KOLANICH** [comment]
I think we don't need separate fields for season and years. We should just combine startDate and endDate into a subschema dateRange and use it everywhere instead of date.

**Comment by chrisdotcode** [comment]
Can you provide examples of what you think that field should look like?

**Comment by KOLANICH** [comment]
```js
date:["2015-01-01","2015-12-31"]//2015 year
date:["2015-03-01","2015-05-31"]//spring 2015
date:["2015-01-01","2015-03-31"]//1st quarter of 2015
```

**Comment by thomasdavis** [comment]
I agree that we should keep dates simply as machine readable, tooling around input and output of dates in resume.jsons can always address the problem.

**Comment by chrisdotcode** [comment]
@KOLANICH I like a list of dates. It also handles the case I just ran into where I did something in 2012, then did it again in 2015. There is currently no way to semantically represent that with just a string.

Unfortunately, in your proposed solution, there's no way to tell when you finished working for a location. Which I see as vital. Maybe a `stillContributing`/`stillWorking` boolean?

Also, I think we should think about dropping string date, and just use actual JS Date objects.

**Comment by stp-ip** [comment]
multiple date tuples using JS dateobjects + ```current``` boolean +1

**Comment by chrisdotcode** [comment]
Turns out I overlooked the word `tuple` in @KOLANICH's suggestion.

Multiple occurrences could therefore be represented as:

`date: [Date(2012), [Date(April, 5, 2015), Date(April, 5, 2015]]`

Where if the last element in the array is a tuple, the work is still current.

How do we feel about this suggestion, as compared to using a `current` boolean?

**Comment by stp-ip** [comment]
Example:
```
date: {
  ["8888-01-01","9999-01-01"] # future (not current) work
  ["2015-01-01","9999-01-01"] # current work
  ["2015-01-01",null], # current work
  ["2013-01-01","2014-01-01"], # past work
}
```
Sounds as minimalistic as possible. As it should be used by tools not humans, going without the boolean simplifies the standard -> +1.

**Comment by KOLANICH** [comment]
>Maybe a stillContributing/stillWorking boolean?
I suggest not to use boolleans/nulls, just omit the second date for half-opened intervals.
```javascript
["2015-01-01"]//i'm doing it since 2015 year
```

**Comment by chrisdotcode** [comment]
@KOLANICH Just above, we discussed @stp-ip's suggestion to not complicate the schema with tuples, and just use a `null`, because using a tuple complicates the schema a lot.

**Comment by KOLANICH** [comment]
I don't see how this complicates. Because of the interval is of variable length, let it be a list not a tuple, but a list with maxlength:2

**Comment by chrisdotcode** [comment]
Because a single list is more complicated than a list of lists.
@stp-ip and I were just discussing how using only a trailing null won't adequately handle all date durations. So the `null` solution by itself insn't entirely adequate.

**Comment by stp-ip** [comment]
Updated my example to make using null clearer. cc @KOLANICH

**Comment by KOLANICH** [comment]
>JavaScript has no formal tuple type
[Tuples](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation) and [lists](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#list-validation) are not js types, they are json schema concepts.

**Comment by chrisdotcode** [comment]
I was not aware of that. In that case, the array of singles/tuples solution handles every possible date case I can think of.

**Comment by KOLANICH** [comment]
```json
{
	"definitions" : {
		"date" : {
			"type" : "string",
			"format" : "date",
			"pattern" : "^\\d{4}-\\d{2}-\\d{2}$"
		},
		"dateRange" : {
			"type" : "array",
			"minItems" : 1,
			"maxItems" : 2,
			"uniqueItems" : true,
			"additionalItems" : true,
			"items" : {
				"$ref" : "#/definitions/date"
			}
		},
		"uniDate" : {
			"anyOf" : [{
					"$ref" : "#/definitions/date"
				}, {
					"$ref" : "#/definitions/dateRange"
				}
			]
		}
	},
	"type" : "object",
	"properties" : {
		"correctD" : {
			"$ref" : "#/definitions/date"
		},
		"correctR" : {
			"$ref" : "#/definitions/dateRange"
		},
		"correctR2" : {
			"$ref" : "#/definitions/dateRange"
		},
		"correctU" : {
			"$ref" : "#/definitions/uniDate"
		},
		"incorrectD1" : {
			"$ref" : "#/definitions/date"
		},
		"incorrectR1" : {
			"$ref" : "#/definitions/dateRange"
		},
		"incorrectU1" : {
			"$ref" : "#/definitions/uniDate"
		},
		"incorrectD2" : {
			"$ref" : "#/definitions/date"
		},
		"incorrectR2" : {
			"$ref" : "#/definitions/dateRange"
		},
		"incorrectU2" : {
			"$ref" : "#/definitions/uniDate"
		},
		"incorrectD3" : {
			"$ref" : "#/definitions/date"
		},
		"incorrectR3" : {
			"$ref" : "#/definitions/dateRange"
		},
		"incorrectU3" : {
			"$ref" : "#/definitions/uniDate"
		},
		"incorrectU4" : {
			"$ref" : "#/definitions/uniDate"
		},
		"incorrectU5" : {
			"$ref" : "#/definitions/uniDate"
		}
	}
}
```
```json
{
	"correctD" : "2015-12-01",
	"correctR" : ["2015-12-01"],
	"correctR2" : ["2015-12-01", "2015-12-03"],
	"correctU1" : "2015-12-01",
	"correctU2" : ["2015-12-01"],
	"correctU3" : ["2015-12-01", "2015-12-03"],
	"incorrectD1" : "sdafsfsdfsdfdsfdsf",
	"incorrectD1" : "1970-01-01T00:00:00.000Z",
	"incorrectR1" : ["2015-12-01", "ololol"],
	"incorrectR2" : ["2015-12-01", "2015-12-03", "2015-12-04"],
	"incorrectR3" : [],
	"incorrectU1" : ["2015-12-01", "ololol"],
	"incorrectU2" : ["2015-12-01", "2015-12-03", "2015-12-04"],
	"incorrectU3" : [],
	"incorrectU4" : "sdafsfsdfsdfdsfdsf",
	"incorrectU5" : "1970-01-01T00:00:00.000Z",
}
```

**Comment by chrisdotcode** [comment]
I think we should go with the following:

Worked for one day:
    { date: ["2015-12-12"] }

    (alternatively:)
    { date: [["2015-12-12", "2015-12-12"]] }

Worked for two months:
    { date: [["2015-12-12", "2016-02-12"]] }

Current work:
    { date: [["2015-12-12"]] } // that is, an array member with a single element

Worked for one day, two months, and presently:

    { date: ["2015-12-11", [["2015-12-12", "2016-02-12"]], ["2016-04-05"]] }

**Comment by stp-ip** [comment]
Updated the example https://github.com/jsonresume/resume-schema/issues/198#issuecomment-157068400 to reflect the current consensus. Much more work for the tools to extract and use dates unfortunately.

**Comment by KOLANICH** [comment]
Do we really need time periods consisting of different intervals?

**Comment by stp-ip** [comment]
I would have just enforced durations such as, but @chrisdotcode made a good point, that it would not be needed for tools and could be made shorter.
date: [["2015-01-01","2015-01-01"]] # one day duration

**Comment by stp-ip** [comment]
Additionally when you enforce durations, how would one represent a year:
```date: [["2013", "2014"]]``` ? would that be one or two years? Would one year be just ```date: [["2013", "2013"]]```

**Comment by stp-ip** [comment]
Considering the feedback from @KOLANICH it could be more consistent to enforce durations and not allow single strings (inside the main date array) to represent a duration.

*Duration implied, when using a list*
Multi date (past, current, future) example:
```
date: [
  ["8888-01-01", "9999-01-01"], # future (not current) work
  ["2015-01-01", "9999-01-01"], # current work
  ["2015-01-01"], # current work
  ["2013-01", "2013-01"], # past work
  ["2013-01-01", "2014-01-01"] # past work
]
```
Multi duration example:
```
date: [
  ["2015-01-01", "9999-01-01"], # future duration
  ["2015-01-01"], # openended duration
  ["2013-01", "2014-01"], # one year duration
  ["2013-01", "2013-01"], # one month duration
  ["2013", "2013"], # one year duration
  ["2013-01", "2013-01"], # one month duration
  ["2013-01-01","2013-01-01"] # one day duration
]
```
Single duration examples:
```
date: [["2013-01", "2014-01"]] # one year duration
date: [["2013", "2013"]] # one year duration
date: [["2013-01"]] # openended duration
date: [["2013-01", "2013-01"]] # one month duration
```

**Comment by KOLANICH** [comment]
You misunderstood me, I was wondering how often will we need lists like you have provided
>
```js
date: [ ["2015-01-01", "9999-01-01"], # future duration ["2015-01-01"], # openended duration ["2013-01", "2014-01"], # one year duration ["2013-01", "2013-01"], # one month duration ["2013", "2013"], # one year duration ["2013-01", "2013-01"], # one month duration ["2013-01-01","2013-01-01"] # one day duration ]
```
and why cant we just use the schema
```json
{
"type":"array",
"items" : { "$ref" : "#/definitions/uniDate" }
}
```
for them.

**Comment by stp-ip** [comment]
So with uniDate only one array would be possible?
```date: ["2013", "2013"]```or ```date: ["2013"]```or ```date: "2013"```
How would multiple durations, dates look like?

**Comment by KOLANICH** [comment]
```js
"date": ["2013", "2013"]//is invalid according to my schema, you should use ["2013-01-01","2013-12-31"] instead
date: ["2013"] //you should use ["2013-01-01"] instead
date: "2013" //you should use ["2013-01-01","2013-12-31"] instead
```

**Comment by stp-ip** [comment]
As we wanted to support ISO 6801, less specific dates are valid. So when we decide to not support less specific dates, we therefore decide to only support the most minimal subset ("YYYY-MM-DD") of ISO 6801. In addition we would reject #142.
So we have to decide, if we allow less specific dates in the schema and therefore in the validator or if we only allow that on the frontend, which then gets rewritten to a specific date aka 2013->2013-01-01.

**Comment by chrisdotcode** [comment]
Yes, less specific dates *should* be valid in the schema: I don't remember the dates for my work history that I still have on my resume from 2006, for example.

I keep going back and forth on a solution because all of the following cases need to be validly representable:

- Working in some year, without the day or month (YYYY, like my 2006 example)
- Working in some year, for the duration of month (YYYY-MM)
- Working in some year, in some month, on some day (YYYY-MM-DD)
- Working in duration of any of the above: (YYYY[-MM[-DD]] to YYYY[-MM[-DD]])
- Any of the above more than once (one duration or a single date, followed by one or more of the same). A practical example of this is me working for Business Corp in 2012 for the entire year, and then doing some contract work with them in May of 2014.

Any solution we decide upon *MUST* be able to handle all of the above real-world cases.

**Comment by chrisdotcode** [comment]
I'm liking @KOLANICH's solution of start/end date pairs:

    date: [(2012, 2013), (2014-04-04, 2015)]

...Actually, using his example, to represent a date in which you don't know the specific end date, you can do the following:

    date: [(2012, 2012)] // sometime in 2012

or:
    date: [(2012-04, 2012-04)]

or for a single day:

    date: [(2012-04-04, 2012-04-04)]

And then a tuple with a single element is open-ended. This solves all of the problems but one: what happens when you have two (or more) open-ended dates?

**Comment by stp-ip** [comment]
I think we basically agree on the syntax and usage.

There are only 2 things left. Allowing less specific dates in @KOLANICH's solution and decide on some edgecases.
One of these is the more than one open-ended dates, this should be invalid. There would be no other need for more than one open-ended dates.

What about having a range ending in the future and one open-ended date? Should probably be possible aka valid, but be handled on the frontend. Right?

**Comment by chrisdotcode** [comment]
@stp-ip My solution above solves the handling of less-specific dates. When more than one on-going date is specified, maybe we should throw an invalid schema error?

A range ending in the future is valid - contract work could end at a specific date, but I don't think working can both be on-going and have a future end date. Maybe we should also throw?

**Comment by stp-ip** [comment]
I meant a code revision supporting the less specific dates ;)

Yeah probably best to throw an error both times.

**Comment by chrisdotcode** [comment]
:+1:

**Comment by chrisdotcode** [comment]
Okay, two more edge cases:

1. How do we handle an on-going date given as not the final item:

    date: [(2015,), (2014-04-05, 2014-05-06)]

2. How do we handle something like this:

    date: [(2015, 2015-03-06)]

I think that this should be a perfectly valid date value, and the parsing of such be left to the theme implementors.

**Comment by stp-ip** [comment]
1. I would say the order is not important and should be sorted on the frontend.
2. I dislike being vague within the data and move so much to the frontend. This could result in quite a few differences in themes, but it should be valid and probably be used as 2015-01-01 on the frontend or even on a layer provided at a lower level.

**Comment by chrisdotcode** [comment]
Sounds good. `(2015, 2015-03-06)`, after all, *is* a valid date range, and I know this because I have fields like this in my own resume.

**Comment by chrisdotcode** [comment]
Unless somebody wants to beat me to it (which is perfectly fine), I'll be making a PR for all changes discussed here.

**Comment by olivif** [comment]
@chrisdotcode sounds great! This will help us make great progress on the Date issues we have open :smile:

**Comment by dawsonbotsford** [comment]
So as a user who wants to make a resume without being a contributor, what is the best way to represent an ongoing job? This could be a deal breaker if there won't be a way to represent ongoing work.

**Comment by aloisdg** [comment]
For the v0, fill the `startDate` and not the `endDate`. 

It may change for the v1, this version is not ready. As a user, @dawsonbotsford , what do you think? Do you have an opinion around the subject based on the current thread?

**Comment by dawsonbotsford** [comment]
I am **not** understanding the current solution for ongoing jobs.

As a response to your most recent comment @aloisdg, I entirely removed the `endDate` field. This creates the following ouput. Is this the best that jsonResume can do?

`2014-11-01 —`

**Comment by aloisdg** [comment]
@dawsonbotsford It is a free from string. You can choose to write "current" or anything else if you want to. Keep in mind, that you are using a v0 not a v1.

**Comment by adrianblynch** [comment]
Could dates that can't be parsed simply be output as-is?

**Comment by chrisdotcode** [comment]
@adrianblynch: We prefer not to take that approach because we favor machine readability.

**Comment by aloisdg** [comment]
For #199, I still think that a endDate set to `null` is the best way to handle it. A flag `current` had some glutter. I dont think it worth it.

**Comment by adrianblynch** [comment]
Without looking into the code, I can't say whether this is straight forward or not, but from a user's point of view, I want to add a date OR I want to specify a non-date like "Present".

@chrisdotcode - What's not machine readable about a string?

**Comment by aloisdg** [comment]
@adrianblynch `null` is not enough? If the start is today or in the past and if the end doesnt exist or is in the future, then this job is a current one.

**Comment by KOLANICH** [comment]
>What's not machine readable about a string?

Because a Date object is not a string. We have to serialize it into string because JSON has no Date type. We stick to the standard used in JS to parse and serialize dates to avoid problems. JSONResume is about defining everything in standard way, not about writing any kind of free-form shit everywhere  you want, because computers cannot understand free-formed texts good enough and reproducibly enough.

**Comment by aloisdg** [comment]
We can use [RFC3339](https://tools.ietf.org/html/rfc3339) like [TOML](https://github.com/toml-lang/toml#user-content-datetime).

```
date1 = 1979-05-27T07:32:00Z
date2 = 1979-05-27T00:32:00-07:00
date3 = 1979-05-27T00:32:00.999999-07:00
```

**Comment by proxa** [comment]
Not sure what the status on this is, but it seems partial dates don't validate like
`2017-01` or `2017`
and adding "Present" obviously doesn't work either.  

It doesn't allow an empty string but will allow the field to be removed completely.

Interesting.  I'm not sure I like the way this strong-arms you into to providing a specific date down to the exact day.

**Comment by jjshoe** [comment]
@thomasdavis why not just drop the "format":"date" from the schema for this?

**Comment by yxliang01** [comment]
+1 for Output as-is when the date can't be parsed to JS `date` object. We are already in 2017. I guess time to make a decision...

**Comment by alienkidmj12** [comment]
anyone any ideas my my work history wont accept a null field for latest ?

**Comment by HyShai** [comment]
It's been 2+ years and this still hasn't been resolved.

**Comment by stp-ip** [comment]
Thanks @HyShai for taking a continued look into jsonresume. Jsonresume is an open source project and has limited capacity. Having an issue open for 2+ years also means that noone contributed a fix in 2+ years. We are working hard to iterate on jsonresume with a new project called github.com/resumic/schema. We are happily taking contributions over there and still take contributions here.

**Comment by darkFunction** [comment]
Bit annoying that nobody mentioned this in 2 years but if you're like me and don't really care if it's machine readable, you can use the `--force` flag to skip validation, eg, `resume export --force resume_fr.html --theme Fr_flat`

**Comment by jjshoe** [comment]
@stp-ip https://github.com/jsonresume/resume-schema/issues/198#issuecomment-302588018

**Comment by noraj** [comment]
Tomorrow we will be in 2019 and we still can't represent a current job.

**Comment by chromedays** [comment]
And here we're in 2020.

**Comment by rbardini** [comment]
I'm able to represent current work with [@rbardini/resume-cli](https://github.com/rbardini/resume-cli), which uses [jsonresume-theme-even](https://github.com/rbardini/jsonresume-theme-even) by default. You can see an example [here](https://github.com/rbardini/resume.rbardini.com).

I've opened [a few PRs to resume-cli](https://github.com/jsonresume/resume-cli/pulls?q=is%3Apr+author%3Arbardini+367+368+369) integrating most changes from the fork, which may help solving this.
