### ISSUE TITLE
v1.0.0 meta issue release strategy

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/resume-schema#220]
As suggested by @aloisdg.

This is the release strategy for `v1.0.0`:
- [ ] Select and resolve all issues for v1.0.0 in resume-schema.
- [ ] Implement all resume-schema=v1.0.0 issues.
- [ ] Select and resolve all issues for v1.0.0 in resume-cli.
- [ ] Implement all resume-cli=v1.0.0 issues.
- [ ] Make sure the server hosted on jsonresume.org is **_fully**_ compatible with all changes made to both of the above.
- [ ] Fix compatibility where broken.
- [ ] Mass publish resume-{schema,cli,server}=v1.0.0.

The cli and server might require re-writes, therefore, our ETA for v1.0.0 is an apt _???_.

**Comment by stp-ip** [comment]
I would add following things:
* [ ] Rebrand with a memorable name for v1.0.0
* [ ] Review the website(s)
* [ ] Get an effort started for a linkedin import/export during beta phase
* [ ] Online editor review (easier design, easily accessible, cli option 'cli online-editor')
* [ ] Reach out to old/new contributors for a community review after v1.0.0-super-early-alpha is available (aka all v1 issues are solved from us)
* [ ] Guide to write (editor) and publish (cli + github pages?) resume


As these things are quite work intensive I would suggest our main todos right now are:
* [ ] Resolve issues for v1.0.0
* [ ] Implement spec for v1.0.0 (link discussions in PRs!)
* [ ] Implement tests for v1.0.0
* [ ] Release v1.0.0-super-early-alpha
* [ ] Get more community feedback for the spec
* [ ] Try to get help from the community for the other issues

**Comment by thomasdavis** [comment]
This all sounds great.

It seems fitting to setup a small "board" of people to ensure the
continuity of the standard, I'm not entirely sure about how to go about
this, so for anyone chiming in with a keen interest, please email me to
setup a time to talk. (Thomasalwyndavis@gmail.com)

**Comment by olivif** [comment]
@thomasdavis I am in, just sent a mail :smile:

**Comment by chrisdotcode** [comment]
Likewise.

**Comment by w0rd-driven** [comment]
`Get an effort started for a linkedin import/export during beta phase`

Hopefully this is an okay spot to chime in but if anyone would like an idea of what's involved in a linkedin import, I've done a little work on the matter here: https://github.com/w0rd-driven/jsonresume-linkedin. This wasn't just to shamelessly plug, but to offer whatever insight or involvement I can.

Due to restrictions from LinkedIn, there's a bit of a hoop to jump through to get data through the API console. The data isn't a 1:1 mapping so I had to be a little opinionated on where things get shoved. Alternatively, there's https://jmperezperez.com/linkedin-to-json-resume/ which mentions waiting up to 72 hours for LinkedIn to send the data dump in individual CSV files. Personally, I'm not a huge fan of either approach but my hacky solution works for me at least (and on my machine(tm)). 

Ideally, having the appropriate API permissions to make the full profile request is preferred but I don't really know how feasible that is for mortals now.


The two big ones for me are LinkedIn and StackOverflow Careers but the latter is just a markdown export that wouldn't be easy to manipulate at all.

**Comment by aloisdg** [comment]
@w0rd-driven Great to see someone working on this!

**Comment by olivif** [comment]
I see we have 49 issues with no milestone assigned. As part of the first bullet we should try to categorize those into v1.0.0 or post-v1 :smile:

**Comment by stp-ip** [comment]
or pre-v1, if they are only support tasks. For example backporting the recent contributing.md to master. Porting some master changes into v1 etc. If noone comes first, I'll create these issues next week and try to work through the other issues for categorization.

**Comment by olivif** [comment]
agreed @stp-ip. I will help out with categorizing current issues. 

Based on the issues I have seen we should think about how we can more effectively track things. We have a lot of old issues, a lot of very long threads with no consensus reached, a lot of cross referencing (like projects for instance and scenarios that will be supported once projects lands) and some duplication as well. 

I am not entirely sure how we can solve it (maybe archive some old issues and start with fresh issues with a summary of the discussions so far?), but in order for us to win back the community I think we need to clean things up a bit.

**Comment by aloisdg** [comment]
1. Keep consensus issues (add them to v1, then close them).
- Move to `revisit` everything else.
- Check once all `revisit`.
- Keep consensus issues (add them to v1, then close them).
- Move to `post-v1` everything else.

Any new idea go to `post-v1`.

**Comment by stp-ip** [comment]
I agree.
I would say. New clean issues for the big changes we want to make. Add a small summary and why different issues are referenced. Then close the different referenced issues.
That would probably outline the big changes as issues, which first need a decision and then a PR.

For discussions, which we deem not generic enough I added the label "Generic Solution Needed" and "Example Needed". Now we can get contributions of specific examples and mark specific ideas as something we need a standard/generic solution for.
Hope that makes sense. In the process I cleaned up our labels.

For the smaller changes we could weed out post-v1 or v1 decisions.

Then we have to finally decide and get PRs for the various issues and cleanup the other repos.
Including tooling, website etc.
* Renaming repos to make them self descriptive.
* Add CoC + Contribution files with a link to our main ones to the repos.
* Start making the website ready for primetime. 
* Fix all issues in the ecosystem. All links are working, what projects should be referenced etc.

I will try to get events, projects, work and tagging related issues sorted and cleaned up. As reading through the different threads just for cleaning up seems like duplicate work.

**Comment by olivif** [comment]
> I see we have 49 issues with no milestone assigned

We are down to 12 unassigned issues currently, great job team! :tada: 


I think the method of aggregating issues and threads works, I feel like we drove a lot of discussions based on the old threads and got lot of good decisions done. 

@stp-ip agreed on the repos cleanup. I was looking through the whole org repos the other day and they are in desperate need of some spring cleaning. I wonder, would it make sense to have a bootstrap/overview repo which we use to control the org in general and all cross-component dependencies? we can also use that for various documentation and contribution docs, more of a start here project.

**Comment by thomasdavis** [comment]
For the technical repo's I've never been a fan of a meta/overview repo and feel like they make everything more confusing over time. First and foremost I will start cleaning all of them, and rename a few.

Will think about how to manage the full technical direction and report back.

**Comment by thomasdavis** [comment]
So I am working on the technical aspect of moving to version 1. If someone else wants to jump on the schema PR's that would be great.
